import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import YouTube from "react-youtube";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Zicket</title>
        <meta name="description" content="Generated by zicket team" />
        <link rel="icon" href="/logoicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <Image
            className={styles.logo}
            src="/blue_logo_new.svg"
            alt="Zicket Logo"
            width={118}
            height={118}
            priority
          />
          <div className={styles.contentInfo}>
            <p className={styles.title}>About Zicket</p>
            <p className={styles.description}>
              Zicket is a solution to the scalping problem raised by 
              <a href="https://www.youtube.com/watch?v=rp3cDq2LiBM"> Vitalik Buterin at 
              ETH Mexico 2022</a>. 
              Currently, people can buy multiple conference tickets at once, which is a problem
              because it encourages ticket misuse and allows bots to resell tickets at inflated prices. 
              Our solution uses zk proofs to allow buyers to remain anonymous, 
              while limiting ticket orders to one per person, also preventing bots from buying ticket and making the tickets 
              non-transferable. Our goal is to prevent ticket scalping and protect buyers{"'"} privacy.
            </p>
            <YouTube videoId='iFZFeTEsz0c'></YouTube>
          </div>
          <div>
            <Link href="/prerequest">
              <button className={styles.button}>
                Let{"'"}s go
              </button>
            </Link>
          </div>
        </div>
      </main>
    </div>
  )
}
